### ISSUE TITLE
ise_id

### ISSUE THREAD

**Issue by ChriszGitHub** [uschoen/1wire#7]
Wie erhalte ich die sie_id ?

Wird in der activ_device.xml nicht angelegt.

In Deinem Beispiel steht:

`                                        <ise_id>29680</ise_id>
`

Ohne die ID erhalte ich nur ein error:

`2016.08.06 22:22:09.513939 error     11535 Connector::HomematicXML /modul/Connector/HomematicXML.pm 75->> can not find field:ise_id. no data send`

**Comment by ChriszGitHub** [comment]
Erledigt. Mann muss nur die Doku von Dir lesen... :)

**Comment by uschoen** [comment]
Der Parameter muss in der Config manuel hinzugefügt werden.
